<?php
/**
 * ExternalProviderTypes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Splitit
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Splitit\Model;
use \Splitit\ObjectSerializer;

/**
 * ExternalProviderTypes Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Splitit
 */
class ExternalProviderTypes
{
    /**
     * Possible values of this enum
     */
    public const MOCK = 'Mock';

    public const VISA = 'Visa';

    public const SPLITIT = 'Splitit';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MOCK,
            self::VISA,
            self::SPLITIT
        ];
    }
}


