<?php
/**
 * MoneyFlows
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Splitit
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Splitit\Model;
use \Splitit\ObjectSerializer;

/**
 * MoneyFlows Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Splitit
 */
class MoneyFlows
{
    /**
     * Possible values of this enum
     */
    public const NOT_DETERMINED = 'NotDetermined';

    public const MONTHLY = 'Monthly';

    public const SCP = 'SCP';

    public const CUSTOM = 'Custom';

    public const PENDING_FUNDING = 'PendingFunding';

    public const CHOOSE = 'Choose';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_DETERMINED,
            self::MONTHLY,
            self::SCP,
            self::CUSTOM,
            self::PENDING_FUNDING,
            self::CHOOSE
        ];
    }
}


