<?php
/**
 * PaymentMethodType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Splitit
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Splitit\Model;
use \Splitit\ObjectSerializer;

/**
 * PaymentMethodType Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Splitit
 */
class PaymentMethodType
{
    /**
     * Possible values of this enum
     */
    public const CARD = 'Card';

    public const SPLITIT_TOKEN = 'SplititToken';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CARD,
            self::SPLITIT_TOKEN
        ];
    }
}


