<?php

/**
 * InstallmentPlanApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Splitit
 * @author   Konfig
 * @link     https://konfigthis.com
 */

/**
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


namespace Splitit\Test\Api;

use \Splitit\Configuration;
use \Splitit\ApiException;
use \Splitit\ObjectSerializer;
use PHPUnit\Framework\TestCase;

class InstallmentPlanApiTest extends TestCase
{

    protected \Splitit\Api\InstallmentPlanApi $api;

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $config = \Splitit\Configuration::getDefaultConfiguration()->setAccessToken('YOUR_ACCESS_TOKEN');
        $this->api = new \Splitit\Api\InstallmentPlanApi($config);
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancel
     *
     * .
     *
     */
    public function testCancel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkEligibility
     *
     * .
     *
     */
    public function testCheckEligibility()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for get
     *
     * .
     *
     */
    public function testGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for post
     *
     * .
     *
     */
    public function testPost()
    {
        $installmentPlanInitiateRequest = [
            "auto_capture" => True,
            "attempt3d_secure" => True,
        ];

        $this->api->post(date("c"), $installmentPlanInitiateRequest);
    }

    /**
     * Test case for post2
     *
     * .
     *
     */
    public function testPost2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for refund
     *
     * .
     *
     */
    public function testRefund()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for search
     *
     * .
     *
     */
    public function testSearch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrder
     *
     * .
     *
     */
    public function testUpdateOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrder2
     *
     * .
     *
     */
    public function testUpdateOrder2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyAuthorization
     *
     * .
     *
     */
    public function testVerifyAuthorization()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
